# Generated by Django 2.0 on 2020-03-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('elogibility', models.CharField(max_length=200)),
                ('fees', models.CharField(max_length=200)),
                ('timing', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fathername', models.CharField(default='', max_length=200)),
                ('mothername', models.CharField(default='', max_length=200)),
                ('gender', models.CharField(default='', max_length=200)),
                ('contactno', models.CharField(default='', max_length=200)),
                ('dateofbirth', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('qualification', models.CharField(max_length=200)),
                ('stream', models.CharField(default='', max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('registrationdate', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'registration',
            },
        ),
        migrations.CreateModel(
            name='studymaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booktitle', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='images/')),
                ('link', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'studymaterial',
            },
        ),
    ]
