# Generated by Django 2.0 on 2020-03-14 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='studymaterial',
            new_name='smaterial',
        ),
        migrations.AlterModelTable(
            name='smaterial',
            table='smaterial',
        ),
    ]
