# Generated by Django 2.0 on 2020-03-14 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200314_1025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='smaterial',
            new_name='studymaterial',
        ),
        migrations.AlterModelTable(
            name='studymaterial',
            table='studymaterial',
        ),
    ]
