# Generated by Django 2.0 on 2020-03-14 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200314_1026'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studymaterial',
        ),
    ]
