# Generated by Django 2.0 on 2020-03-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_delete_studymaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='studymaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booktitle', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='images/')),
                ('link', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'studymaterial',
            },
        ),
    ]
