# Generated by Django 2.0 on 2020-03-18 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_studymaterial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='elogibility',
            new_name='eligibility',
        ),
    ]
