# Generated by Django 2.0 on 2020-03-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20200318_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='success',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=255)),
                ('rollno', models.CharField(max_length=300)),
                ('clearcourse', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'success',
            },
        ),
    ]
