# Generated by Django 2.0 on 2020-04-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_success'),
    ]

    operations = [
        migrations.CreateModel(
            name='vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=255)),
                ('post', models.CharField(max_length=255)),
                ('noofvacancy', models.CharField(max_length=300)),
                ('eligibility', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'vacancy',
            },
        ),
    ]
