# Generated by Django 2.0 on 2020-05-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20200427_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='prefferedtime',
            field=models.CharField(default='', max_length=200),
        ),
    ]
