# Generated by Django 2.0 on 2020-05-24 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_video_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='video',
        ),
    ]
